import { NextRequest, NextResponse } from 'next/server'

const OLLAMA_API_URL = process.env.OLLAMA_API_URL || 'http://localhost:11434'
const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'mistral'

interface OllamaMessage {
  role: 'user' | 'assistant'
  content: string
}

async function generateWithOllama(prompt: string): Promise<string> {
  const messages: OllamaMessage[] = [
    {
      role: 'user',
      content: `You are an expert PowerPoint presentation creator. Based on the following prompt, create a detailed presentation structure in JSON format.

Respond ONLY with valid JSON in this exact format:
{
  "title": "Presentation Title",
  "slides": [
    {
      "title": "Slide Title",
      "content": ["Bullet point 1", "Bullet point 2", "Bullet point 3"]
    }
  ]
}

Make sure to:
- Create 3-5 informative slides
- Each slide should have a title and 2-4 bullet points
- Content should be relevant and well-structured
- Use simple, clear language

Prompt: ${prompt}`,
    },
  ]

  try {
    const response = await fetch(`${OLLAMA_API_URL}/api/chat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: OLLAMA_MODEL,
        messages,
        stream: false,
      }),
    })

    if (!response.ok) {
      throw new Error(`Ollama API error: ${response.statusText}`)
    }

    const data = await response.json()
    const content = data.message?.content || ''

    // Extract JSON from the response
    const jsonMatch = content.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      throw new Error('Invalid JSON response from Ollama')
    }

    const presentationData = JSON.parse(jsonMatch[0])
    return JSON.stringify(presentationData)
  } catch (error) {
    throw new Error(`Failed to generate presentation: ${error instanceof Error ? error.message : 'Unknown error'}`)
  }
}

function generatePPTX(presentationData: any): Buffer {
  // Since we can't easily use pptxgenjs in the API route without proper setup,
  // we'll create a basic PPTX structure
  const PptxGenJS = require('pptxgenjs')

  const pres = new PptxGenJS()
  pres.defineLayout({ name: 'LAYOUT1', width: 10, height: 7.5 })
  pres.defineLayout({ name: 'LAYOUT2', width: 10, height: 7.5 })

  // Title Slide
  const titleSlide = pres.addSlide()
  titleSlide.background = {
    fill: '667eea',
  }
  titleSlide.addText(presentationData.title || 'Presentation', {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1.5,
    fontSize: 54,
    bold: true,
    color: 'ffffff',
    align: 'center',
    fontFace: 'Arial',
  })
  titleSlide.addText('Generated by AI', {
    x: 0.5,
    y: 4.2,
    w: 9,
    h: 0.6,
    fontSize: 18,
    color: 'e0e0e0',
    align: 'center',
    fontFace: 'Arial',
  })

  // Content Slides
  if (Array.isArray(presentationData.slides)) {
    presentationData.slides.forEach((slide: any) => {
      const contentSlide = pres.addSlide()
      contentSlide.background = { fill: 'ffffff' }

      // Slide Title
      contentSlide.addText(slide.title || 'Slide', {
        x: 0.5,
        y: 0.4,
        w: 9,
        h: 0.8,
        fontSize: 40,
        bold: true,
        color: '667eea',
        fontFace: 'Arial',
      })

      // Add horizontal line
      contentSlide.addShape(pres.ShapeType.line, {
        x: 0.5,
        y: 1.3,
        w: 9,
        h: 0,
        line: { color: '667eea', width: 2 },
      })

      // Bullet Points
      let yPos = 1.8
      if (Array.isArray(slide.content)) {
        slide.content.forEach((point: string) => {
          contentSlide.addText('• ' + point, {
            x: 1,
            y: yPos,
            w: 8.5,
            h: 0.8,
            fontSize: 16,
            color: '333333',
            fontFace: 'Arial',
            wrap: true,
          })
          yPos += 1
        })
      }
    })
  }

  // Closing Slide
  const closingSlide = pres.addSlide()
  closingSlide.background = {
    fill: '764ba2',
  }
  closingSlide.addText('Thank You!', {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1.5,
    fontSize: 54,
    bold: true,
    color: 'ffffff',
    align: 'center',
    fontFace: 'Arial',
  })
  closingSlide.addText('Generated with PowerPoint Generator', {
    x: 0.5,
    y: 4.2,
    w: 9,
    h: 0.6,
    fontSize: 16,
    color: 'e0e0e0',
    align: 'center',
    fontFace: 'Arial',
  })

  return pres.write({ outputType: 'arraybuffer' })
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { prompt } = body

    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json(
        { error: 'Invalid prompt' },
        { status: 400 }
      )
    }

    // Generate presentation content with Ollama
    const presentationJson = await generateWithOllama(prompt)
    const presentationData = JSON.parse(presentationJson)

    // Generate PPTX file
    const pptxBuffer = generatePPTX(presentationData)

    // Return as downloadable file
    return new NextResponse(pptxBuffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="presentation-${Date.now()}.pptx"`,
      },
    })
  } catch (error) {
    console.error('Error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal server error' },
      { status: 500 }
    )
  }
}